name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
  workflow_dispatch:  # ✅ manual trigger enabled

jobs:
  # your existing job definitions go here...
